### ISSUE TITLE
Change App name and App icon

### ISSUE THREAD

**Issue by nyx-code** [csi-vitpune/FlutterMagazine#10]
1. Create a new Icon that suits the Magazine app and replace it with the default one. (For IOS optional. It would be really great if you add an icon for IOS too).
2. Change the default app name to some appropriate name.

**Comment by suhas-kadu** [comment]
I would like to solve this issue

**Comment by nyx-code** [comment]
Great!! Try it :)

**Comment by nyx-code** [comment]
Thank You both @suhas-kadu  @deliciafernandes for sending PR. I will review it as soon as possible and merge the proper one :)
