### ISSUE TITLE
The named parameter 'colors' isn't defined in the LinearGradient widget

### ISSUE THREAD

**Issue by nyx-code** [csi-vitpune/FlutterMagazine#3]
There were recent updates regarding Flutter so one of the params named as 'color' in the LinearGradient widget is removed so make appropriate changes to fix that Warning message.

**Comment by deliciafernandes** [comment]
Hey @nyx-code! I'm not facing this issue on my local.
Check this link out, I think its an android studio issue: https://github.com/flutter/flutter/issues/63908

**Comment by nyx-code** [comment]
@deliciafernandes what flutter version you are using?

**Comment by nyx-code** [comment]
Okay, it does look like a minor issue from an android studio. 
I am closing this issue now there is no need for PR. 
Thanks :)
